<?php

/**
 * Implements hook_flag_default_flags
 */
function flag_application_flag_default_flags() {
    $flags = [];
// Exported flag: "Flag Application".
    $flags['flag_application'] = [
        'entity_type' => 'node',
        'title' => 'Flag Application',
        'global' => '0',
        'types' =>
            [
            ],
        'flag_short' => 'Apply',
        'flag_long' => 'Apply for this',
        'flag_message' => 'Thanks for applying',
        'unflag_short' => 'Remove your application',
        'unflag_long' => 'Remove your application for this from the site',
        'unflag_message' => 'Your application has been removed',
        'unflag_denied_text' => '',
        'link_type' => 'toggle',
        'weight' => 0,
        'show_in_links' =>
            [
                'full' => 'full',
                'teaser' => 'teaser',
                'rss' => 0,
                'search_index' => 0,
                'search_result' => 0,
            ],
        'show_as_field' => 1,
        'show_on_form' => 0,
        'access_author' => '',
        'show_contextual_link' => 0,
        'i18n' => 0,
        'api_version' => 3,
    ];
    return $flags;
}

/**
 * Act on an object being flagged.
 *
 * @param flag_flag $flag
 *  The flag object.
 * @param int $entity_id
 *  The id of the entity the flag is on.
 * @param $account
 *  The user account performing the action.
 * @param $flagging_id
 *  The flagging entity.
 * Implements hook_flag_flag
 * @throws Exception
 */
function flag_application_flag_flag($flag, $entity_id, $account, $flagging) {
    /*dpm($flag);
    dpm($entity_id);
    dpm($account);*/
    dpm($flagging);

    if ($flag->name == 'flag_application') {
        $node_id = db_insert('flag_application')
            ->fields([
                'flagging_id' => $flagging->flagging_id,
                'status' => 0,
            ])
            ->execute();
    }
}

/**
 * Act on an object being unflagged.
 *
 * This is invoked after the flag count has been decreased, but before the
 * flagging entity has been deleted.
 *
 * @param $flag
 *  The flag object.
 * @param int $entity_id
 *  The id of the entity the flag is on.
 * @param $account
 *  The user account performing the action.
 * @param $flagging
 *  The flagging entity.
 */
function flag_application_flag_unflag($flag, $entity_id, $account, $flagging) {

    if ($flag->name == 'flag_application') {
        $deleted = db_delete('flag_application')
            ->condition('flagging_id', $flagging->flagging_id)
            ->execute();
    }
}
